import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "./components/theme-provider"
import { ModeToggle } from "./components/ui/mode-toggle"
import { UserProvider } from "./contexts/UserContext"

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`antialiased`}
      >
        <UserProvider>
          <ThemeProvider
            attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange
          >
            <div className="fixed top-4 right-4">
              <ModeToggle />
            </div>
            {children}
          </ThemeProvider>
        </UserProvider>
      </body>
    </html>
  );
}
